interval: "5s" 

monitor:
  local:
    enabled: true
    process_filters:
      keywords: ["python", "vim"]
      users: ["christian"]
      groups: []

  remote:
    - host: "sol"
      user: "christian"
      port: 5822
      ssh_key: "~/.ssh/id_ed25519"
      proxy_jump: "venus"
      process_filters:
        keywords: ["python", "python3"]
        users: ["christian"]
        groups: []
    - host: "helix"
      user: "christian"
      port: 5822
      ssh_key: "~/.ssh/id_ed25519"
      proxy_jump: "venus"
      process_filters:
        keywords: ["python", "python3"]
        users: ["christian"]
        groups: []

